hmrc/submit-vat-return-frontend

app/config/FrontendAppConfig.scala
app/config/filters/ExcludingCSRFFilter.scala
app/config/filters/ServiceFilters.scala
app/config/filters/WhitelistFilter.scala
conf/application.conf
test/config/filters/WhitelistFilterSpec.scala
test/mocks/MockConfig.scala

Here are the app-config prs that need merging as well:

BTAT-5616 Added whitelist and csrf filters

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/connectors/VatSubscriptionConnector.scala
app/connectors/httpParsers/CustomerDetailsHttpParser.scala
app/connectors/httpParsers/ResponseHttpParsers.scala
app/models/CustomerDetails.scala
app/models/ErrorModel.scala
app/services/VatSubscriptionService.scala
build.sbt
conf/application.conf
it/base/BaseISpec.scala
it/connectors/VatSubscriptionConnectorISpec.scala
it/resources/application.conf
it/utils/WireMockHelper.scala
project/plugins.sbt
test/base/BaseSpec.scala
test/connectors/httpParsers/CustomerDetailsHttpParserISpec.scala
test/mocks/MockConfig.scala
test/models/CustomerDetailsSpec.scala
test/services/VatSubscriptionServiceSpec.scala

[DM] BTAT-5692 Connector and Service layer added for vat-subscription

---

app/testOnly/config/TestOnlyAppConfig.scala
app/testOnly/connectors/DynamicStubConnector.scala
app/testOnly/controllers/DynamicStubController.scala
app/testOnly/models/DataModel.scala
app/testOnly/models/SchemaModel.scala
build.sbt
conf/application.conf
conf/testOnlyDoNotUseInAppConf.routes

Added test-only routes for populating stub

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/ConfirmationController.scala
app/views/confirmation_view.scala.html
conf/app.routes
conf/application.conf
conf/messages
it/pages/ConfirmationPageISpec.scala
test/assets/messages/ConfirmationPageMessages.scala
test/controllers/ConfirmationControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala
test/mocks/MockConfig.scala
test/mocks/MockMandationPredicate.scala
test/views/ConfirmationViewSpec.scala

This needs an app-config pr merging prior to this going in
- [app-config-base-pr] https://github.com/hmrc/app-config-base/pull/2098

BTAT-5839 Added confirmation view and controller

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/ConfirmSubmissionController.scala
app/controllers/SubmitFormController.scala
app/views/confirm_submission.scala.html
app/views/submit_form.scala.html
app/views/templates/formatters/navigationBreadcrumb.scala.html
build.sbt
conf/application.conf
conf/messages
test/controllers/ConfirmSubmissionControllerSpec.scala
test/mocks/MockConfig.scala
test/views/ConfirmSubmissionViewSpec.scala
test/views/SubmitFormViewSpec.scala
test/views/templates/formatters/NavigationBreadcrumbTemplateSpec.scala

Added breadcrumbs to submit form and confirm page

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/connectors/VatReturnsConnector.scala
app/connectors/httpParsers/SubmitVatReturnHttpParser.scala
app/models/SubmissionSuccessModel.scala
app/models/vatReturnSubmission/SubmissionModel.scala
app/models/vatReturnSubmission/SubmissionSuccessModel.scala
build.sbt
conf/application.conf
it/base/BaseISpec.scala
it/connectors/VatReturnsConnectorISpec.scala
it/stubs/VatReturnsStub.scala
test/connectors/httpParsers/SubmitVatReturnHttpParserSpec.scala
test/mocks/MockConfig.scala

Added connector and parser for POSTing to vat-returns

---

app/controllers/ConfirmSubmissionController.scala
app/controllers/predicates/MandationStatusPredicate.scala
app/services/VatReturnsService.scala
conf/logback-test.xml
it/base/BaseISpec.scala
it/pages/ConfirmSubmissionPageSpec.scala
it/pages/SubmitFormPageSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/mocks/service/MockVatReturnsService.scala
test/services/VatReturnsServiceSpec.scala

Added submission of nine box return data to backend

---

app/common/ConfigKeys.scala
app/config/ErrorHandler.scala
app/config/FrontendAppConfig.scala
app/config/features/Feature.scala
app/config/features/Features.scala
app/controllers/ConfirmSubmissionController.scala
app/controllers/SubmitFormController.scala
app/services/DateService.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/testOnly/views/singleCheckbox.scala.html
build.sbt
conf/application.conf
conf/testOnlyDoNotUseInAppConf.routes
it/base/BaseISpec.scala
it/pages/ConfirmSubmissionPageSpec.scala
it/pages/SubmitFormPageSpec.scala
it/stubs/VatObligationsStub.scala
project/plugins.sbt
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/mocks/MockConfig.scala
test/mocks/service/MockDateService.scala

[BTAT-6097] Added check preventing future returns being submitted

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/predicates/MandationStatusPredicate.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/stubAgentClientLookupAgentAction.scala.html
app/views/confirmation_view.scala.html
app/views/errors/incorrect_mandation_user.scala.html
conf/application.conf
conf/messages
conf/testOnlyDoNotUseInAppConf.routes
test/assets/CustomerDetailsTestAssets.scala
test/assets/messages/IncorrectMandationMessages.scala
test/base/BaseSpec.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala
test/mocks/MockConfig.scala
test/views/ConfirmationViewSpec.scala
test/views/errors/IncorrectMandationUserViewSpec.scala

Here are the corresponding app-config-prs below:

BTAT-6157 Added graceful error handling for user with incorrect mandation status

---

.github/pull_request_template

Created initial PR template - see body for example

---

conf/application.conf

set session timeout to 900 seconds

---

app/controllers/ConfirmSubmissionController.scala
app/views/errors/submission_error.scala.html
conf/messages
test/assets/messages/SubmissionErrorMessages.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/views/errors/SubmissionErrorViewSpec.scala

[BTAT-6239] - added submission-error page

---

app/views/confirm_submission.scala.html
app/views/confirmation_view.scala.html
app/views/main_template.scala.html
app/views/submit_form.scala.html
public/javascripts/ga.js

Btat 6236 Added GA events

---

app/audit/AuditConnector.scala
app/audit/AuditService.scala
app/audit/models/ExtendedAuditModel.scala
app/audit/models/SubmitVatReturnAuditModel.scala
app/config/FrontendAppConfig.scala
app/controllers/ConfirmSubmissionController.scala
app/utils/JsonObjectSugar.scala
test/audit/mocks/MockAuditingService.scala
test/audit/models/SubmitVatReturnAuditModelSpec.scala
test/audit/models/TestExtendedAuditModel.scala
test/base/BaseSpec.scala
test/connectors/VatSubscriptionConnectorSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/views/ConfirmSubmissionViewSpec.scala
test/views/ConfirmationViewSpec.scala
test/views/SubmitFormViewSpec.scala
test/views/errors/IncorrectMandationUserViewSpec.scala
test/views/errors/SubmissionErrorViewSpec.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

[BTAT-6232] - added audit event for SubmitVatReturn

---

app/common/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf

Here are the app-config prs for this:

Added language toggle feature switch

---

app/config/FrontendAppConfig.scala
app/controllers/LanguageController.scala
app/views/govuk_wrapper.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
test/controllers/LanguageControllerSpec.scala
test/mocks/MockConfig.scala
test/views/ConfirmationViewSpec.scala
test/views/SubmitFormViewSpec.scala
test/views/errors/IncorrectMandationUserViewSpec.scala
test/views/errors/SubmissionErrorViewSpec.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

BTAT-6287 Added welsh toggle and controller

---

app/controllers/ConfirmSubmissionController.scala
app/controllers/SubmitFormController.scala
it/pages/ConfirmSubmissionPageSpec.scala
it/pages/SubmitFormPageSpec.scala

Added decoding of period key for use in service

---

app/views/confirmation_view.scala.html
test/views/ConfirmationViewSpec.scala

BTAT-6394 fixed redirect URL

---

app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html

BTAT-6393 Moved language toggle out of govuk wrapper into main template

---

app/controllers/SubmitFormController.scala
test/controllers/SubmitFormControllerSpec.scala

Fixes a bug on the submit for the 9 box entry page, where it didn't use the period key to match with the correct obligation. This meant if a user had multiple obligations open, it could submit for the wrong obligation or not allow them to submit at all

Fixed matching of period key on submission

---

app/common/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf

Added feature switch to toggle NRS submissions

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/connectors/VatReturnsConnector.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/models/nrs/SuccessModel.scala
app/services/VatReturnsService.scala
conf/application.conf
it/connectors/VatReturnsConnectorISpec.scala
it/pages/ConfirmSubmissionPageSpec.scala
it/stubs/VatReturnsStub.scala
it/utils/NrsTestData.scala
test/connectors/httpParsers/NrsSubmissionHttpParserSpec.scala
test/mocks/MockConfig.scala
test/services/VatReturnsServiceSpec.scala

[BTAT-6418] Added connector and service for NRS submission to backend

---

app/services/VatReturnsService.scala

Removed overrides for default values

---

app/services/VatReturnsService.scala
test/assets/NrsTestData.scala
test/services/VatReturnsServiceSpec.scala

Added the header info and to populate model as per the NRS spec.
Added tests

Added the header info and to populate model as per the NRS spec.

---

app/models/nrs/Language.scala
app/utils/ReceiptDataHelper.scala
conf/messages.cy
test/models/nrs/LanguageSpec.scala
test/utils/ReceiptDataHelperSpec.scala

[DM] BTAT-6416 Added declaration builder/helper

---

app/audit/models/journey/FailureAuditModel.scala
app/audit/models/journey/StartAuditModel.scala
app/audit/models/journey/SuccessAuditModel.scala
app/controllers/ConfirmSubmissionController.scala
app/controllers/SubmitFormController.scala
build.sbt
test/audit/models/journey/FailureAuditModelSpec.scala
test/audit/models/journey/StartAuditModelSpec.scala
test/audit/models/journey/SuccessAuditModelSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala

BTAT-6483 Added 3 audit events - start, success and failure of submission journey

---

app/audit/models/journey/FailureAuditModel.scala
app/audit/models/journey/StartAuditModel.scala
app/audit/models/journey/SuccessAuditModel.scala
test/audit/models/journey/FailureAuditModelSpec.scala
test/audit/models/journey/StartAuditModelSpec.scala
test/audit/models/journey/SuccessAuditModelSpec.scala

I've also updated the confluence page where the events are documented.

BTAT-5619 Updated audit event names to make them unique

---

app/audit/models/NrsErrorAuditModel.scala
app/audit/models/NrsSuccessAuditModel.scala
app/audit/models/SubmitNrsModel.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/controllers/ConfirmSubmissionController.scala
it/connectors/VatReturnsConnectorISpec.scala
test/connectors/httpParsers/NrsSubmissionHttpParserSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala

[BTAT-6503] - added nrs audit events

---

app/views/templates/inputs/moneyInput.scala.html

[DM] [BTAT-6498] Changed input field types to tel

---

app/config/FrontendAppConfig.scala
app/controllers/SignOutController.scala
app/views/govuk_wrapper.scala.html
conf/app.routes
test/controllers/SignOutControllerSpec.scala
test/mocks/MockConfig.scala

BTAT-6456 Added dynamic exit survey identifier based on user type

---

app/views/confirm_submission.scala.html
test/views/ConfirmSubmissionViewSpec.scala

[BTAT-6508] - changing to use definition list on check your answers page

---

app/views/main_template.scala.html
build.sbt
conf/messages
test/assets/messages/AuthMessages.scala
test/assets/messages/BaseMessages.scala
test/assets/messages/ConfirmSubmissionMessages.scala
test/assets/messages/ConfirmationPageMessages.scala
test/assets/messages/MtdMandationMessages.scala
test/assets/messages/SessionExpiredMessages.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/predicates/AuthPredicateSpec.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala
test/views/ConfirmSubmissionViewSpec.scala
test/views/errors/MtdMandationUserViewSpec.scala
test/views/errors/SessionExpiredViewSpec.scala
test/views/errors/SubmissionErrorViewSpec.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

[BTAT-6512] - added suffix's to pageTitles

---

app/controllers/SignOutController.scala
test/controllers/SignOutControllerSpec.scala

BTAT-6535 Added exception recovery to sign out auth logic

---

app/views/submit_form.scala.html
conf/messages
test/assets/messages/SubmitFormPageMessages.scala
test/controllers/SubmitFormControllerSpec.scala

BTAT-6516 - updated the error summary message with the GDS Design 

---

app/testOnly/views/stubAgentClientLookupAgentAction.scala.html
app/testOnly/views/stubAgentClientUnauth.scala.html
app/views/confirmation_view.scala.html
app/views/errors/unauthorised_agent.scala.html
app/views/submit_form.scala.html

BTAT-6556 Add role to button-styled anchor tags

---

app/models/nrs/Metadata.scala
build.sbt
it/assets/NrsAssets.scala
it/utils/NrsTestData.scala
test/assets/NrsTestData.scala

Updated NRS metadata values to match assessment page

---

conf/messages
conf/messages.cy
test/assets/messages/BaseMessages.scala
test/views/GovUkWrapperSpec.scala

BTAT-6637 Updated nav title for agent journey

---

app/views/govuk_wrapper.scala.html
conf/messages
conf/messages.cy
test/views/GovUkWrapperSpec.scala

BTAT-6583 added navTitle.vat

---

app/audit/models/NrsErrorAuditModel.scala
app/audit/models/NrsSuccessAuditModel.scala
app/controllers/ConfirmSubmissionController.scala
build.sbt
test/audit/models/NrsErrorAuditModelSpec.scala
test/audit/models/NrsSuccessAuditModelSpec.scala

Tweaked audit models

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/govuk_wrapper.scala.html
build.sbt
conf/application.conf
test/mocks/MockConfig.scala
test/views/GovUkWrapperSpec.scala

Here are the app config prs:
* [app-config-base](https://github.com/hmrc/app-config-base/pull/2511)
* [app-config-production](https://github.com/hmrc/app-config-production/pull/4417)

BTAT-6652 Added accessibility statement link

---

app/views/submit_form.scala.html
conf/messages
conf/messages.cy
it/assets/NrsAssets.scala
test/assets/messages/ConfirmSubmissionMessages.scala
test/assets/messages/ConfirmationPageMessages.scala
test/utils/ReceiptDataHelperSpec.scala

BTAT-6661 - updated the Page title for Submit Vat Return pages

---

app/views/submit_form.scala.html
build.sbt
test/base/BaseSpec.scala
test/views/SubmitFormViewSpec.scala

BTAT-6691 fixed welsh for 9 box

---

app/controllers/predicates/AuthPredicate.scala
app/views/errors/unauthorised_agent.scala.html
app/views/errors/unauthorised_non_agent.scala.html
test/controllers/predicates/AuthPredicateSpec.scala
test/mocks/MockAuth.scala
test/views/errors/UnauthorisedAgentViewSpec.scala
test/views/errors/UnauthorisedNonAgentViewSpec.scala

BTAT-6783 Added correct sign out href for unauth error pages

---

app/views/main_template.scala.html
public/js/errorFocus.js

[BTAT-6909] - added javascript to auto-focus to error-summary

---

app/connectors/VatReturnsConnector.scala
app/connectors/httpParsers/SubmitVatReturnHttpParser.scala
build.sbt
test/connectors/httpParsers/SubmitVatReturnHttpParserSpec.scala

Updated submission logging to include VRN and period key for debugging

---

app/common/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/ConfirmSubmissionController.scala
app/services/VatReturnsService.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
it/base/BaseISpec.scala
it/pages/ConfirmSubmissionPageSpec.scala
test/base/BaseSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala

[DM] [BTAT-7111] Removed NRS Submission feature switch

---

app/controllers/ConfirmSubmissionController.scala
test/controllers/ConfirmSubmissionControllerSpec.scala

BTAT-7223 Fixed issue with wrong year in URL

---

app/config/ErrorHandler.scala
app/views/templates/error_template.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
project/build.properties
test/assets/messages/AuthMessages.scala
test/assets/messages/BaseMessages.scala
test/assets/messages/SessionExpiredMessages.scala
test/assets/messages/SubmissionErrorMessages.scala
test/config/ErrorHandlerSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/AuthPredicateSpec.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala
test/views/ConfirmationViewSpec.scala
test/views/errors/SessionExpiredViewSpec.scala

Toggled XSS protection, added Welsh support to error pages & smart apostrophes

---

app/views/submit_form.scala.html

**As-is layout on `master`**
**New layout after change**

BTAT-7230 Moved error summary above H1

---

app/common/SessionKeys.scala
app/controllers/ConfirmSubmissionController.scala
app/controllers/SubmitFormController.scala
app/controllers/predicates/HonestyDeclarationAction.scala
build.sbt
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/HonestyDeclarationActionSpec.scala

Also added TODOs as placeholders for predicate to be integrated as part of BTAT-7570

Added new predicate for honesty declaration check

---

app/controllers/HonestyDeclarationController.scala
app/controllers/SubmitFormController.scala
app/forms/HonestyDeclarationForm.scala
app/views/honesty_declaration.scala.html
app/views/templates/inputs/checkboxHelper.scala.html
build.sbt
conf/app.routes
conf/messages
conf/messages.cy
project/plugins.sbt
test/controllers/HonestyDeclarationControllerSpec.scala
test/forms/HonestyDeclarationFormSpec.scala
test/views/HonestyDeclarationViewSpec.scala
test/views/templates/inputs/CheckboxHelperSpec.scala

[BTAT-7568] - added view, controller, routes, form, checkbox helper for honesty declaration

---

app/controllers/HonestyDeclarationController.scala
app/forms/HonestyDeclarationForm.scala
app/views/honesty_declaration.scala.html
build.sbt
test/controllers/HonestyDeclarationControllerSpec.scala
test/views/HonestyDeclarationViewSpec.scala

[BTAT-7571] - added form validation to honesty declaration

---

app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html

BTAT-7578 Moving language toggle to gov uk template

---

app/controllers/ConfirmSubmissionController.scala
app/controllers/HonestyDeclarationController.scala
app/controllers/SubmitFormController.scala
app/controllers/predicates/HonestyDeclarationAction.scala
it/pages/ConfirmSubmissionPageSpec.scala
it/pages/SubmitFormPageSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/HonestyDeclarationControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/HonestyDeclarationActionSpec.scala
test/mocks/MockHonestyDeclarationAction.scala

[BTAT-7570] - updated honesty declaration routing

---

public/css/palette.css

BTAT-7636 Updated confirmation h1 box colour

---

app/config/filters/ExcludingCSRFFilter.scala
conf/application.conf

Fixed Zap Issues, removed duplicate modules

---

app/common/MandationStatuses.scala
app/controllers/predicates/MandationStatusPredicate.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala

BTAT-7764 - Catered for new Mandation Statuses

---

conf/application.conf

[BTAT-8119] Updated assets and fixed deprecation warnings

---

app/views/ConfirmationView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ConfirmationPageMessages.scala
test/views/ConfirmationViewSpec.scala

BTAT-7898 Updating agent confirmation page content

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/GovUkWrapper.scala.html
conf/application.conf
run.sh
test/mocks/MockConfig.scala

Please ensure that this PR is also merged: https://github.com/hmrc/app-config-base/pull/4067

BTAT-8279 Added tracking consent banner

---

build.sbt

Also small clean up to the file to remove unnecessary elements, refine scoverage exclusions, and bump up the Scala version.

Disabled JUnitXmlReportPlugin

---

build.sbt
conf/application.conf
it/base/SessionCookieBaker.scala
project/build.properties
project/plugins.sbt

BTAT-8312 Removed usages of uk.gov.hmrc.http.SessionKeys

---

app/views/HonestyDeclaration.scala.html
app/views/SubmitForm.scala.html
app/views/templates/ErrorSummary.scala.html
app/views/templates/inputs/CheckboxHelper.scala.html
conf/messages
conf/messages.cy
test/views/HonestyDeclarationViewSpec.scala
test/views/templates/ErrorSummarySpec.scala
test/views/templates/inputs/CheckboxHelperSpec.scala

BTAT-8324 - error corrections

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/GovUkWrapper.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/mocks/MockConfig.scala

* [ x] Branch is rebased with master
* [x ] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [x ] Ran [submit-vat-return-acceptance-tests](https://github.com/hmrc/submit-vat-return-acceptance-tests) (see README of repo)

[BTAT-8592] Updated tracking consent script

---

app/common/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/ConfirmSubmissionController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitch.scala.html
app/views/ConfirmationView.scala.html
conf/application.conf
test/base/BaseSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/views/ConfirmationViewSpec.scala

[BTAT-8609] - removed redundant feature switches

---

app/config/FrontendAppConfig.scala
build.sbt
conf/application.conf

BTAT-8652 Updating sign out urls to use bas-gateway

---

conf/application.conf

Changed nine box feature switch value to true

---

app/controllers/ConfirmSubmissionController.scala
app/utils/HashUtil.scala
build.sbt

 [BTAT-8762] Refactor to change permanence of HashUtil, added logging to submitToNrs

---

app/common/SessionKeys.scala
app/controllers/predicates/AuthPredicate.scala
app/models/CustomerDetails.scala
it/connectors/VatSubscriptionConnectorISpec.scala
test/assets/CustomerDetailsTestAssets.scala
test/base/BaseSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/AuthPredicateSpec.scala
test/mocks/MockAuth.scala
test/models/CustomerDetailsSpec.scala
test/utils/ReceiptDataHelperSpec.scala

[BTAT-8856] - added check for future insolvency

---

app/controllers/predicates/AuthPredicate.scala
app/models/CustomerDetails.scala
build.sbt
project/plugins.sbt
test/controllers/predicates/AuthPredicateSpec.scala
test/models/CustomerDetailsSpec.scala

BTAT-8929 Tweak to insolvency access logic; removing agent insolvency checks

---

app/views/ConfirmationView.scala.html
build.sbt

I also tested the affected page with the Validity plugin

BTAT-8986 Removed invalid HTML attribute

---

app/views/templates/inputs/MoneyInput.scala.html
public/css/submitVat-v3.css
test/views/templates/inputs/MoneyInputTemplateSpec.scala

Updating 9 box return input following advice from accessibility team

---

app/assets/stylesheets/application.scss
app/testOnly/views/FeatureSwitch.scala.html
app/testOnly/views/StubAgentClientLookup.scala.html
app/testOnly/views/StubAgentClientLookupAgentAction.scala.html
app/testOnly/views/StubAgentClientUnauth.scala.html
app/views/ConfirmSubmission.scala.html
app/views/ConfirmationView.scala.html
app/views/HonestyDeclaration.scala.html
app/views/MainTemplate.scala.html
app/views/MainTemplateOriginal.scala.html
app/views/SubmitForm.scala.html
app/views/errors/MtdMandatedUser.scala.html
app/views/errors/SessionExpired.scala.html
app/views/errors/SubmissionError.scala.html
app/views/errors/UnauthorisedAgent.scala.html
app/views/errors/UnauthorisedNonAgent.scala.html
build.sbt
conf/app.routes
project/plugins.sbt
test/views/errors/MtdMandationUserViewSpec.scala
test/views/errors/SubmissionErrorViewSpec.scala

BTAT-9295 MainTemplate for submit vat return

---

app/views/ConfirmSubmission.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ConfirmSubmissionMessages.scala
test/views/ConfirmSubmissionViewSpec.scala

BTAT-9298 upgrade ConfirmSubmission to new govuk assets

---

app/views/ConfirmationView.scala.html
test/views/ConfirmationViewSpec.scala

BTAT-9299 - Update Confirmation View in Submit Vat Return FE

---

app/views/ConfirmationView.scala.html

BTAT-buttonFix - Updated the confirmation view with the correct button colour

---

app/views/HonestyDeclaration.scala.html
test/views/HonestyDeclarationViewSpec.scala

BTAT-9296 Upgrading honesty dec to govuk assets

---

app/audit/AuditService.scala
app/config/filters/ServiceFilters.scala
app/controllers/SignOutController.scala
app/controllers/predicates/MandationStatusPredicate.scala
build.sbt
project/plugins.sbt
test/connectors/VatSubscriptionConnectorSpec.scala
test/mocks/MockHttp.scala
test/services/VatReturnsServiceSpec.scala

BTAT-9355 Updated bootstrap and other dependencies

---

app/views/SubmitForm.scala.html
conf/messages
conf/messages.cy
test/views/SubmitFormViewSpec.scala

BTAT-9380 Updated HTML structure and page title of 9 box submit view

---

app/views/ConfirmSubmission.scala.html
app/views/HonestyDeclaration.scala.html
app/views/MainTemplate.scala.html
app/views/SubmitForm.scala.html
test/views/ConfirmSubmissionViewSpec.scala
test/views/SubmitFormViewSpec.scala

BTAT-9384 Move Back Link out of main template

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/HonestyDeclarationController.scala
app/controllers/predicates/DDInterruptPredicate.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
build.sbt
conf/application.conf
test/base/BaseSpec.scala
test/controllers/HonestyDeclarationControllerSpec.scala
test/controllers/predicates/DDInterruptPredicateSpec.scala
test/mocks/MockConfig.scala
test/mocks/MockDDInterruptPredicate.scala

Btat 9376 Added DD Interrupt Predicate

---

app/views/ConfirmSubmission.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ConfirmSubmissionMessages.scala
test/views/ConfirmSubmissionViewSpec.scala

[BTAT-9381] Updated HTML for wcag issues

---

app/views/MainTemplate.scala.html
conf/messages
conf/messages.cy

BTAT-9436 remove unused messages and govukHeader

---

app/forms/HonestyDeclarationForm.scala
app/utils/Money.scala
app/utils/ReceiptDataHelper.scala
app/utils/StopOnFirstFail.scala
app/views/ConfirmationView.scala.html
app/views/templates/formatters/money/DisplayMoney.scala.html
build.sbt
test/utils/MoneySpec.scala

I had to update a CSS selector in the acceptance tests because of the VACLUF assets migration: https://github.com/hmrc/submit-vat-return-acceptance-tests/pull/59

[BTAT-9502] Remove play-ui dependency

---

app/assets/stylesheets/application.scss
app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
conf/application.conf
test/mocks/MockConfig.scala
test/views/MainTemplateSpec.scala

app-config-base PR: https://github.com/hmrc/app-config-base/pull/6111

BTAT-9598 Added dynamic service URL to header

---

build.sbt
project/plugins.sbt

Btat 9642 Removed play-frontend-govuk

---

app/forms/SubmitVatReturnForm.scala
build.sbt
conf/app.routes
conf/messages
conf/messages.cy
test/forms/SubmitVatReturnFormSpec.scala

BTAT-9672 Added error message for use of decimal places in boxes 6-9

---

app/views/SubmitForm.scala.html
build.sbt
test/assets/messages/SubmitFormPageMessages.scala
test/views/MainTemplateSpec.scala
test/views/SubmitFormViewSpec.scala

BTAT-9689 Redesign of 9-box submit form page

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
conf/application.conf
conf/messages
conf/messages.cy
it/base/BaseISpec.scala
test/assets/messages/BaseMessages.scala
test/assets/messages/SubmitFormPageMessages.scala
test/mocks/MockConfig.scala
test/views/HonestyDeclarationViewSpec.scala
test/views/MainTemplateSpec.scala

BTAT-9716 - Service name and service link updated

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/predicates/AuthPredicate.scala
app/views/errors/UserInsolventError.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/UserInsolventMessages.scala
test/mocks/MockAuth.scala
test/mocks/MockConfig.scala
test/views/errors/UserInsolventErrorSpec.scala

app-config-base pr - https://github.com/hmrc/app-config-base/pull/6413

[BTAT-9853]-Added insolvency view and tests to submit-vat-return-frontend

---

app/common/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
conf/application.conf
test/mocks/MockConfig.scala

[BTAT-10014] - Update submit-vat-return-frontend

---

app/views/ConfirmSubmission.scala.html
test/views/ConfirmSubmissionViewSpec.scala

[BTAT-10144] Added prevent double click attribute to button

---

app/views/templates/MTDSignUpBanner.scala.html
build.sbt
conf/messages
conf/messages.cy
test/views/templates/MTDSignUpBannerSpec.scala

[BTAT-10480] Update signup banner content

---

app/views/templates/formatters/dates/DisplayDate.scala.html
conf/messages

BTAT-10599 Refactor of date helper and adding english month messages

---

conf/messages
conf/messages.cy

BTAT-10612 Audit of message files

---

build.sbt
conf/application.conf

[BTAT-10917] Update container ID for GTM

---

app/controllers/SignOutController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
app/views/templates/formatters/money/DisplayMoney.scala.html
build.sbt
it/integrationAssets/NrsAssets.scala
project/plugins.sbt
test/audit/mocks/MockAuditingService.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/controllers/predicates/MandationStatusPredicateSpec.scala
test/mocks/service/MockDateService.scala
test/mocks/service/MockMandationStatusService.scala
test/mocks/service/MockVatSubscriptionService.scala

* [x Ran [submit-vat-return-acceptance-tests](https://github.com/hmrc/submit-vat-return-acceptance-tests) (see README of repo)

Btat 10962 Upgrade to Scala 2.13

---

build.sbt
project/plugins.sbt

[BTAT-10962] Upgraded bootstrap-play version

---

app/views/templates/formatters/money/DisplayMoney.scala.html

Ran Wave, Axe, Validity and Voiceover as check

BTAT-11181 remove aria-hidden-attribute

---

app/assets/stylesheets/application.scss
app/views/ConfirmSubmission.scala.html
app/views/SubmitForm.scala.html

[BTAT-11261] - Updating where gov-uk hint shouldn't be used

---

app/assets/stylesheets/application.scss
app/views/SubmitForm.scala.html
project/plugins.sbt

[BTAT-11261] - govuk-hint bug fix

---

build.sbt
conf/messages.cy
test/assets/messages/SubmitFormPageMessages.scala

BTAT-11303 Update all instances of HMRC in Welsh translations

---

app/connectors/VatObligationsConnector.scala
app/connectors/VatReturnsConnector.scala
app/connectors/VatSubscriptionConnector.scala
app/connectors/httpParsers/CustomerDetailsHttpParser.scala
app/connectors/httpParsers/MandationStatusHttpParser.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/connectors/httpParsers/ResponseHttpParsers.scala
app/connectors/httpParsers/SubmitVatReturnHttpParser.scala
app/connectors/httpParsers/VatObligationsHttpParser.scala
app/services/MandationStatusService.scala
app/services/VatObligationsService.scala
app/services/VatReturnsService.scala
app/services/VatSubscriptionService.scala
build.sbt
it/connectors/VatSubscriptionConnectorISpec.scala
project/plugins.sbt
test/connectors/VatSubscriptionConnectorSpec.scala
test/controllers/ConfirmSubmissionControllerSpec.scala
test/controllers/SubmitFormControllerSpec.scala
test/mocks/service/MockMandationStatusService.scala
test/mocks/service/MockVatObligationsService.scala
test/mocks/service/MockVatReturnsService.scala
test/mocks/service/MockVatSubscriptionService.scala
test/services/MandationStatusServiceSpec.scala
test/services/VatObligationsServiceSpec.scala
test/services/VatReturnsServiceSpec.scala

[BTAT-11376] Removed HttpGet aliases

---

app/audit/AuditService.scala
app/forms/HonestyDeclarationForm.scala
app/models/nrs/Language.scala
app/views/templates/formatters/dates/DisplayDate.scala.html
app/views/templates/formatters/dates/DisplayDateRange.scala.html
it/pages/SubmitFormPageSpec.scala
test/assets/messages/ConfirmSubmissionMessages.scala
test/assets/messages/SubmitFormPageMessages.scala
test/views/SubmitFormViewSpec.scala
test/views/templates/formatters/dates/DisplayDateRangeTemplateSpec.scala
test/views/templates/formatters/dates/DisplayDateTemplateSpec.scala

[BTAT-11382] Use non-breaking spaces in dates

---

app/views/MainTemplate.scala.html

[BTAT-11503] Removed beta banner

---

README.md

[BTAT-11555] Updating README with a description of the service

---

build.sbt
conf/logback.xml
test/audit/models/SubmitVatReturnAuditModelSpec.scala
test/utils/MoneySpec.scala

DL-12647 fixing unit test compilation warns and logger file

---

app/config/FrontendAppConfig.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
build.sbt
conf/testOnlyDoNotUseInAppConf.routes
project/build.properties
project/plugins.sbt

DL-16021: Java21 upgrade
